### ISSUE TITLE
Possible too many requests error on `getMahasiswa` query

### ISSUE THREAD

**Issue by grikomsn** [sutanlab/kampus-scraper#3]
First of all, this is a wonderful project! 👏 

Spent some time testing queries and encountered many times of `unexpected character` errors if sending too much `getMahasiswa` queries for some time. Below are screenshots and query results for failed and successful queries:

<details>
<summary>Failed query</summary>

![image](https://user-images.githubusercontent.com/8220954/72677431-f49faa80-3ace-11ea-8dc9-fab95e78dff0.png)

```json
{
  "error": "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
}
```

</details>

<details>
<summary>Successful query</summary>

![image](https://user-images.githubusercontent.com/8220954/72677535-f322b200-3acf-11ea-8b82-4407839f71fb.png)

```json
{
  "data": {
    "getMahasiswa": {
      "nim": "062014106379",
      "nama": "GRIKO MUHAMMAD SULTAN NIBRAS",
      ...
    }
  }
}
```

</details>

Any references on where should I look in the codebase? Would love to help this project, but I'm fairly new to Apollo. 😄

**Comment by sutanlab** [comment]
Well, its because Zeit <https://zeit.co> limit the request timeout only 10s
in free plan. Here is the log:

2020-01-19T08:16:32.364Z 27bfd9df-8bc7-4bb7-82bf-926530fb3119 Task timed
out after 10.01 seconds

Currently i dont know to handle the response message if that error occurs
again,

Pada tanggal Min, 19 Jan 2020 pukul 15.23 Griko Nibras <
notifications@github.com> menulis:

**Comment by sutanlab** [comment]
Well, its because Zeit <https://zeit.co> limit the request timeout only 10s in free plan.

Here is the log:

`2020-01-19T08:16:32.364Z 27bfd9df-8bc7-4bb7-82bf-926530fb3119 Task timed
out after 10.01 seconds`

---

But, currently i dont know to handle the response message if that error occurs
again because i've no idea to see application log in Zeit. If you know to handle that error, you should handle in `schema/mahasiswa.js` at `getMahasiswa()` resolver. Or maybe we can listen the error globally in `server.js`.

**Comment by sutanlab** [comment]
Well, it because Zeit <https://zeit.co> limit the request timeout only 10s in free plan.

Here is the runtime log from Zeit:

```
2020-01-19T08:16:32.364Z 27bfd9df-8bc7-4bb7-82bf-926530fb3119 Task timed
out after 10.01 seconds
```

But, currently i dont know to handle the response message if that error occurs
again, because i've no idea to see application log in Zeit. If you know to handle that error, you should handle in `schema/mahasiswa.js` at `getMahasiswa()` resolver. Or maybe we can listen the error globally in `server.js`.

**Comment by albasyir** [comment]
Make it possible!, donate developer now hahahaha LoL

**Comment by sutanlab** [comment]
deployed on aws. https://kampus.sutanlab.id
